
bastionusername=bastion4
bastionhostname=gitlab.kodera.hr
targetusername=almir

home_dir="/home/$targetusername"
docker_dir="$home_dir/docker.d/"
docker_container_name_get_proxies="free_proxy_list_net_get_proxies"
docker_image_name_get_proxies="free_proxy_list_net_get_proxies_image"
docker_image_version_get_proxies="1.1"
docker_container_name_check_proxies="free_proxy_list_net_check_proxies"
docker_image_name_check_proxies="free_proxy_list_net_check_proxies_image"
docker_image_version_check_proxies="1.1"
docker_container_check_proxies_spawn_number=6

getfxrealtimedata_dockerfile=Dockerfile-get-forex-realtime-data
getfxrealtimedata_imagename=get-forex-realtime-data
getfxrealtimedata_imageversion=0.6
getfxrealtimedata_containername=get_forex_realtime_data
getfxrealtimedata_containername_conf="$home_dir/get_forex_realtime_data.conf"
getfxrealtimedata_datadir="/home/almir/docker.conf/get-forex-realtime-data"

